name: croppy
description: A fully customizable image cropper for Flutter. Mobile-first, but supports Web and Desktop platforms.
version: 0.1.0
homepage: https://github.com/kekland/croppy

environment:
  sdk: '>=3.0.0 <4.0.0'
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter

  cassowary: ^0.4.2
  cupertino_icons: ^1.0.5

  equatable: ^2.0.5

  image: ^4.0.17
  path_provider: ^2.0.15

  vector_math: ^2.1.4

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
